version: '3.1'

services:
  nestjs:
    image: amadu12/modakbul:latest
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    env_file:
      - .env
